### ISSUE TITLE
ReferenceError: config is not defined

### ISSUE THREAD

**Issue by mermao1** [carmolim/olx-monitor#11]
Olá.
Minha primeira vez rodando o script, e tentei utilizar minhas próprias pesquisas em `config.js`, mas sempre acontece esse mesmo erro de `config is not defined`.
Dessa última vez, tentei utilizando a mesma URL retirada do exemplo no README, mas o mesmo erro ocorre. Alguma sugestão?

Cópia do erro abaixo
```
root@proxy:~/olx-monitor# node index.js
/root/olx-monitor/config.js:1
config.urls = ['https://sp.olx.com.br/sao-paulo-e-regiao/centro/celulares/iphone?cond=1&cond=2&pe=1600&ps=600&q=iphone']
^

ReferenceError: config is not defined
    at Object.<anonymous> (/root/olx-monitor/config.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/olx-monitor/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

```

Conteúdo de config.js:
```
root@proxy:~/olx-monitor# cat config.js
config.urls = ['https://sp.olx.com.br/sao-paulo-e-regiao/centro/celulares/iphone?cond=1&cond=2&pe=1600&ps=600&q=iphone']
root@proxy:~/olx-monitor#
```

**Comment by mermao1** [comment]
Acho que não li o README direito ou não está muito claro, mas o arquivo `sample-config.js` deve ser utilizado como `config.js`. 
Funcionou.
