### ISSUE TITLE
ERROR Scraping failed

### ISSUE THREAD

**Issue by Possomato** [carmolim/olx-monitor#22]
Olá @carmolim! 
Desde já muito obrigado por compartilhar esse projeto conosco, tem me ajudado muito!

Estou enfrentando um problema após a exclusão e reinstalação do projeto. Ao listar os anúncios, ocorre este erro. O processo identifica a presença de certos anúncios, mas em seguida, ocorre um erro e o sistema tenta reiniciar a busca, voltando novamente para o mesmo erro

```
2024-01-04 09:55:25 INFO  Ads found: 2047
2024-01-04 09:55:26 ERROR No adverts found
{}
Error: No adverts found
    at scrapePage (/Users/possomato/Downloads/olx-monitor-main/components/Scraper.js:72:19)
    at scraper (/Users/possomato/Downloads/olx-monitor-main/components/Scraper.js:36:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-04 09:55:26 ERROR Scraping failed
{}
Error: Scraping failed
    at scrapePage (/Users/possomato/Downloads/olx-monitor-main/components/Scraper.js:113:15)
    at scraper (/Users/possomato/Downloads/olx-monitor-main/components/Scraper.js:36:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by carmolim** [comment]
Olá @Possomato, que bom que está sendo útil para você!

Uma dúvida, você está usando a última versão da branch main?

**Comment by Possomato** [comment]
Nesta que eu tive esse erro estava usando a última versão da branch main, mas um pouco após eu baixei a cloundflare e consegui rodar normalmente igual antes

**Comment by mermao1** [comment]
Olá.
Eu estava há umas semanas sem usar, e ontem reinstalei do zero a branch main, que apresentou os mesmos problemas da postagem. Resolvi mudar pra branch cloudflare e está funcionando certinho.

PS: em ambas as branchs tive que instalar separadamente o "form-data", que parece necessário mas não instala durante o "npm install"

**Comment by carmolim** [comment]
Acabei de atualizar a `main` acho que acabei fazendo uma bagunça na hora de mergear as branches, mas agora está certinho.
