### ISSUE TITLE
Erro ao executar

### ISSUE THREAD

**Issue by thcasssio** [carmolim/olx-monitor#28]
Olá, tudo bem?

Acredito que configurei tudo direitinho, porém quando rodo da esse erro:

`root@sip:/opt/olx-monitor/src# node index.js
/opt/olx-monitor/src/node_modules/cycletls/dist/index.js:46
    exit = exit ?? true;
                 ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/opt/olx-monitor/src/components/CycleTls.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
`

Poderia me ajudar por favor?

**Comment by carmolim** [comment]
Olá @thcasssio parece ser um problema em uma dependência que o projeto usa. Você está tentando rodar em qual sistema operacional?
